name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/nadekobot"
      docker_label_author: "Efina"
      docker_label_title: "Docker Nadekobot"
      docker_label_description: "Nadekobot rebuild version for arm"
      version_detecter: true
      version_detecter_var: "NADEKO_VERSION="
      platforms: "linux/amd64"
